name: Cron Reminders

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  trigger-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger reminder processing
        run: |
          # Replace with your actual Vercel domain
          VERCEL_DOMAIN="your-vercel-domain.vercel.app"

          echo "Triggering reminder processing at $(date)"

          # Make the request to the cron endpoint
          response=$(curl -s -w "\n%{http_code}" -X GET "https://$VERCEL_DOMAIN/api/cron-reminders")

          # Extract the response body and status code
          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | head -n -1)

          echo "Response status: $http_code"
          echo "Response body: $response_body"

          # Check if the request was successful
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Reminder processing triggered successfully"
          else
            echo "❌ Failed to trigger reminder processing"
            exit 1
          fi
